# PR Pipeline - Validate commits and run tests
when:
  - event: pull_request

labels:
  platform: linux/amd64

steps:
  # Validate conventional commit format
  - name: commitlint
    image: node:22-alpine
    commands:
      - npm install -g @commitlint/cli @commitlint/config-conventional
      - |
        echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
      - |
        # Get the PR commits and validate them
        git log --format=%s origin/${CI_COMMIT_TARGET_BRANCH}..HEAD | while read -r msg; do
          echo "Validating commit message"
          echo "$msg" | commitlint
        done

  # Build and run tests
  - name: build-and-test
    image: mcr.microsoft.com/dotnet/sdk:10.0
    commands:
      - dotnet restore
      - dotnet build -c Release
      - dotnet test -c Release --logger "console;verbosity=detailed"
    depends_on: [commitlint]
