# Minimal test pipeline
when:
  - event: push
    branch: main

labels:
  platform: linux/amd64

steps:
  - name: test
    image: alpine
    commands:
      - echo "Pipeline is working!"
      - echo "Branch is $CI_COMMIT_BRANCH"
